# Generated by Django 4.0.1 on 2022-02-02 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='Resume',
        ),
    ]
